<h1>主辦的活動</h1>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>活動名稱</th>
            <th>票種</th>
            <th>販售時間</th>
            <th>報名人數</th>
            <th>活動變更</th>
            <th>上下架</th>
            <th>報名人資料</th>
        </tr>
    </thead>
   <?php $publishKey = Zend_Registry::get('publishKey'); ?>
    <tbody>
        <?php foreach ($this->paginator as $event): ?>
        <tr>
            <td><a href="<?php echo $this->formActionUrl('new', 'registration', 'user', array('event' => $event['url'])) ?>"><?php echo $event['name'] ?></a></td>
            <td> <?php echo $event['ticketName'] ?></td>
            <td><?php echo $event['sale_start'] ?>~<?php echo $event['sale_end'] ?></td>
            <td> <?php echo $event['register_num'] . '/' . $event['quantity'] ?></td>
            <td><a href="<?php echo $this->formActionUrl('edit', 'event', null, array('event' => $event['url'])) ?>">編輯</a></td>
            <td>
                <div class="btn-group">
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    <?php echo $publishKey[$event['publish']] ?> <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="<?php echo $this->formActionUrl('publish', 'dashboard', null, array('event' => $event['url'])) ?>">上架</a></li>
                    <li><a href="<?php echo $this->formActionUrl('draft', 'dashboard', null, array('event' => $event['url'])) ?>">下架</a></li>
                  </ul>
                </div>
            </td>
            <td><a href="<?php echo $this->formActionUrl('order', 'dashboard', null, array('event' => $event['url'])) ?>">訂單</a></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>

<div class="row text-center">
    <div class="col-lg-12">
        <ul class="pagination">
        <?php echo $this->paginationControl($this->paginator,
                                            'Sliding',
                                            'common/pagination.phtml'); ?>
        </ul>
    </div>
</div>