<?php date_default_timezone_set('Asia/Taipei'); ?>
<div class="container">
		<?php foreach($this->paginator as $key => $data): ?>
		<div class="row">

            <div class="col-lg-7 col-md-7">
                <?php echo $data['event_sn'] ?>
                <img src="<?php echo $this->baseUrl('img/' . $data['image']) ?>" class="img-responsive">
            </div>

            <div class="col-lg-5 col-md-5">
                <h3><?php echo $data['name'] ?></h3>
                <h4><span class="glyphicon glyphicon-time"></span><?php echo date("Y-m-d H:i", strtotime($data['start_time'])) . '~' . date("Y-m-d H:i", strtotime($data['end_time'])) ?>
                </h4>
                <p><?php echo $data['description'] ?></p>
                <a class="btn btn-primary" href="<?php echo $this->formActionUrl('new', 'registration', null, array('event' => $data['url'])) ?>">報名去 <span class="glyphicon glyphicon-chevron-right"></span></a>
            </div>

        </div>
        <?php endforeach; ?>

        <hr>

        <div class="row text-center">
            <div class="col-lg-12">
                <ul class="pagination">
                <?php echo $this->paginationControl($this->paginator,
				                                    'Sliding',
				                                    'index/pagination.phtml'); ?>
                  
                </ul>
            </div>
        </div>
       
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright © Company 2013</p>
                </div>
            </div>
        </footer>

    </div>