<!DOCTYPE html>
<html>
<?php date_default_timezone_set('Asia/Taipei'); ?>
<script>
    $(document).ready(function() {
        $('select').change(function(event) {
            var isValid = false;
            $('select option:selected').each(function(index) {
                if ($(this).val() > 0) {
                    isValid = true;
                };
            });

            if (isValid) {
                $('[type=submit]').show();
            } else{
                $('[type=submit]').hide();
            };
        });
    });
</script>
<body>
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <h1><?php echo $this->event['name'] ?></h1>

                </p>
                <hr>
                <h3>
                    <span class="glyphicon glyphicon-time"></span><?php echo date("Y-m-d H:i", strtotime($this->event['start_time'])) . '~' . date("Y-m-d H:i", strtotime($this->event['end_time'])) ?>
                </h3>
                <hr>
                <img src="/img/<?php echo $this->baseUrl($this->event['image']) ?>" class="img-responsive">
                <hr>
                <?php echo $this->event['description'] ?>

                <hr>

                <form action="<?php echo $this->formActionUrl('purchase', null, null, array('event' => $this->params)) ?>" method="post">
                    <h4>票券資訊</h4>
                    <table class="table table-bordered">
                    	<thead>
                    		<tr>
                    			<th>票種</th>
                    			<th>販售時間</th>
                    			<th>價格</th>
                    			<th>數量</th>
                    		</tr>
                    	</thead>
                    	<tbody>
                    		<?php
                    			foreach ($this->tickets as $ticket):
                    				$ticketLeft = $ticket['quantity'] - $ticket['register_num'];
                                    $ticketMax = (($ticketLeft - $ticket['max_order']) > 0) ? $ticket['max_order'] : $ticketLeft ;
                    				$options = array();
                    				for ($value=0; $value <= $ticketMax ; $value++) { 
                    					$options[$value] = $value;
                    				}
                    		?>
                    			<tr>
                    				<td><?php echo $ticket['ticketName'] ?></td>
                    				<td><?php echo date("Y-m-d H:i", strtotime($ticket['sale_start'])) . '~' . date("Y-m-d H:i", strtotime($ticket['sale_end'])) ?></td>
                    				<td><?php echo $ticket['price'] ?></td>
                    				<?php if (($ticket['quantity'] - $ticket['register_num']) > 0): ?>
                                        <td><?php echo $this->formSelect('ticket[' . $ticket['ticket_sn'] .']', 0, array('class' => 'form-control'), $options); ?>
                                        </td>
                                    <?php else: ?>
                                        <td class="text-danger">已售完</td>            
                                    <?php endif ?>
                    			</tr>
                    		<?php endforeach ?>
                    	</tbody>
                    </table>
                    <div><?php echo $this->formCheckbox('agree', NULL, array('class' => 'agree',
                                                                            'required' => '',
                                                                            'id'       => 'checkbox_id'
                                                                            )) 
                         ?>
                        <label for="checkbox_id">我同意<a href="#">服務條款</a>及<a href="#">隱私權政策</a></label>
                    </div>
                    <?php if (!$this->isRegistered): ?>
                    <div class="bg-danger">
                        <h3>請先登入或是註冊後再做報名</h3>
                        <div>
                            <a href="<?php echo $this->formActionUrl('login', 'user', null, null) ?>" class="btn btn-primary active" role="button">登入</a>
                            <a href="<?php echo $this->formActionUrl('signup', 'user', null, null) ?>" class="btn btn-primary active" role="button">註冊</a>
                        </div>
                    </div>
                    <?php endif ?>
                    <?php if ($this->isRegistered): ?>
                        <button type="submit" class="btn btn-primary" style="display:none;">下一步</button>
                    <?php endif ?>
                </form>
                <!-- <div class="well">
                    <h4>Leave a Comment:</h4>
                    <form role="form">
                        <div class="form-group">
                            <textarea class="form-control" rows="3"></textarea>
                        </div>
                        <button type="button" class="btn btn-primary">報名</button>
                    </form>
                </div> -->

                <hr>
            </div>

            <div class="col-lg-4">
                <div class="well">
                    <h4>活動地址</h4>
                    <?php $CountyKey = Zend_Registry::get('CountyKey'); ?>
                    <p>  <a href="http://maps.google.com.tw/maps?hl=zh-TW&q=<?php echo $CountyKey[$this->event['county']] . $this->event['address'] ?>" target="_blank"><?php echo $CountyKey[$this->event['county']] . $this->event['address'] ?></a></p>
                    <!-- <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </span>
                    </div> -->
                    <!-- /input-group -->
                </div>
                <!-- /well -->
                <div class="well">
                    <h4>Popular Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#dinosaurs">Dinosaurs</a>
                                </li>
                                <li><a href="#spaceships">Spaceships</a>
                                </li>
                                <li><a href="#fried-foods">Fried Foods</a>
                                </li>
                                <li><a href="#wild-animals">Wild Animals</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#alien-abductions">Alien Abductions</a>
                                </li>
                                <li><a href="#business-casual">Business Casual</a>
                                </li>
                                <li><a href="#robots">Robots</a>
                                </li>
                                <li><a href="#fireworks">Fireworks</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Bootstrap's default wells work great for side widgets! What is a widget anyways...?</p>
                </div>
                <!-- /well -->
            </div>
        </div>

        <hr>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Company 2013</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->
</body>

</html>