<!DOCTYPE html>
<html>
<?php date_default_timezone_set('Asia/Taipei'); ?>
<body>
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <h1><?php echo $this->event['name'] ?></h1>

                </p>
                <hr>
                <p>
                    <span class="glyphicon glyphicon-time"></span><?php echo date("Y-m-d H:i", strtotime($this->event['start_time'])) . '~' . date("Y-m-d H:i", strtotime($this->event['end_time'])) ?>
                </p>
                <form method="post" action="<?php echo $this->formActionUrl('confirm', null, null, array('event' => $this->params)) ?>">    
                <h3>訂單資訊</h3>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>票種</th>
                            <th>數量</th>
                            <th>價格</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php 
                            $totalTickets = 0; 
                            $i = 0;
                        ?>
                        <?php foreach ($this->orders as $order): ?>
                            <?php echo $this->formHidden('sn[' . $i . ']', $order['ticket_sn']) ?>
                            <?php echo $this->formHidden('quantity[' . $i . ']', $order['quantity']) ?>
                            <?php $i++; ?>
                            <tr>
                                <td><?php echo $order['name'] ?></td>
                                <td><?php echo $order['price'] . ' x ' . $order['quantity'] ?></td>
                                <td><?php echo $order['total']; 
                                        $totalTickets += $order['total'];
                                    ?></td>
                            </tr>
                        <?php endforeach ?>
                            <tr>
                                <th colspan="2">總金額</th>
                                <th><?php echo $totalTickets ?></th>
                            </tr>
                    </tbody>
                </table>
                <table class="table table-bordered">
                        <tr>
                            <th>欄位</th>
                            <th>表格</th>
                        </tr>
                        <tbody>
                            <?php if ($this->required['name']): ?>
                                <tr>
                                    <td>姓名</td>
                                    <td>
                                        <?php 
                                            echo $this->formText('form[name]',
                                                               (isset($this->user_account->username)) ? $this->user_account->username : null,
                                                                array('class' => 'form-control', 'placeholder' => '姓名', 'required' => 'required')
                                                        )
                                         ?>
                                    </td>
                                </tr>    
                            <?php endif ?>
                            <?php if ($this->required['email']): ?>
                                <tr>
                                    <td>Email</td>
                                    <td>
                                        <?php 
                                            echo $this->formText('form[email]',
                                                                (isset($this->user_account->email)) ? $this->user_account->email : null,
                                                                array('class' => 'form-control', 'placeholder' => 'email', 'required' => 'required')
                                                        )
                                         ?>
                                    </td>
                                </tr>    
                            <?php endif ?>
                            <?php if ($this->required['phone']): ?>
                                <tr>
                                    <td>電話</td>
                                    <td>
                                        <?php 
                                            echo $this->formText('form[phone]',
                                                                (isset($this->user_account->phone)) ? $this->user_account->phone : null,
                                                                array('class' => 'form-control', 'placeholder' => '09xx123456', 'required' => 'required')
                                                        )
                                         ?>
                                    </td>
                                </tr>    
                            <?php endif ?>
                            <?php if ($this->required['beneficiary']): ?>
                                <tr>
                                    <td>受益人</td>
                                    <td>
                                        <?php 
                                            echo $this->formText('form[beneficiary]',
                                                                                null,
                                                                array('class' => 'form-control', 'placeholder' => '', 'required' => 'required')
                                                        )
                                         ?>
                                    </td>
                                </tr>    
                            <?php endif ?>
                            <?php if ($this->required['ID']): ?>
                                <tr>
                                    <td>身份證字號</td>
                                    <td>
                                        <?php 
                                            echo $this->formText('form[ID]',
                                                                                null,
                                                                array('class' => 'form-control', 'placeholder' => '', 'required' => 'required')
                                                        )
                                         ?>
                                    </td>
                                </tr>    
                            <?php endif ?>
                            <?php if ($this->required['birthday']): ?>
                                <tr>
                                    <td>
                                        生日
                                    </td>
                                    <td>
                                        <div class="form-group form-inline">
                                            <label class="control-label">西元</label>
                                            <input class="form-control" name="year" required>
                                            <label class="control-label">年</label>
                                            <input class="form-control" name="month" required>
                                            <label class="control-label">月</label>
                                            <input class="form-control" name="day" required>
                                            <label class="control-label">日</label>
                                        </div>
                                    </td>
                                </tr>
                             <?php endif ?> 
                            <?php if ($this->required['gender']): ?>
                                <tr>
                                    <td>
                                        性別
                                    </td>
                                    <td>
                                        <div class="form-group">
                                            <?php echo $this->formSelect('form[gender]', 1, array('class' => 'form-control', 'required' => 'required'), array(1 => '--', 2 => '男', 3 =>'女')) ?>
                                        </div>
                                    </td>
                                </tr>    
                            <?php endif ?>
                            <?php if ($this->required['group']): ?>
                                <tr>
                                    <td>
                                        牧區
                                    </td>
                                    <td>
                                        <div class="form-group">
                                            <?php echo $this->formSelect('groups', 0, array('class' => 'form-control', 'required' => 'required'), $this->groups) ?>
                                        </div>
                                    </td>
                                </tr>
                            <?php endif ?>
                            <?php if ($this->required['food']): ?>
                                <tr>
                                    <td>
                                        飲食
                                    </td>
                                    <td>
                                        <div class="form-group">
                                            <?php echo $this->formSelect('form[food]', 1, array('class' => 'form-control', 'required' => 'required'), array(1 => '--', 2 => '葷食', 3 =>'素食', 4 => '不訂便當')) ?>
                                        </div>
                                    </td>
                                </tr>    
                            <?php endif ?>
                            <?php if ($this->required['other']): ?>
                                <tr>
                                    <td>
                                        其他事項
                                    </td>
                                    <td>
                                        <div class="form-group">
                                            <textarea cols="80" class="form-control" required rows="10" form="other"></textarea>
                                        </div>
                                    </td>
                                </tr>    
                            <?php endif ?>
                            
                        </tbody>
                    </table>
                  
                    <button type="submit" class="btn btn-primary">確認報名</button>
                </form>

                <hr>
            </div>

            <div class="col-lg-4">
                <div class="well">
                    <h4>活動地址</h4>
                    <p>  <a href="http://maps.google.com.tw/maps?hl=zh-TW&q=<?php echo $this->event['county'] ?><?php echo $this->event['address'] ?>" target="_blank"><?php echo $this->event['address'] ?></a></p>
                    <!-- <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </span>
                    </div> -->
                    <!-- /input-group -->
                </div>
                <!-- /well -->
                <div class="well">
                    <h4>Popular Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#dinosaurs">Dinosaurs</a>
                                </li>
                                <li><a href="#spaceships">Spaceships</a>
                                </li>
                                <li><a href="#fried-foods">Fried Foods</a>
                                </li>
                                <li><a href="#wild-animals">Wild Animals</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#alien-abductions">Alien Abductions</a>
                                </li>
                                <li><a href="#business-casual">Business Casual</a>
                                </li>
                                <li><a href="#robots">Robots</a>
                                </li>
                                <li><a href="#fireworks">Fireworks</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Bootstrap's default wells work great for side widgets! What is a widget anyways...?</p>
                </div>
                <!-- /well -->
            </div>
        </div>

        <hr>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Company 2013</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->
</body>

</html>