<script src="//code.jquery.com/jquery-1.9.1.js"></script>

  <?php echo $this->headScript()->appendFile('/js/datetime-picker/bootstrap-datetimepicker.min.js', 'text/javascript'); ?>
  <?php echo $this->headScript()->appendFile('/js/datetime-picker/locales/bootstrap-datetimepicker.zh-TW.js', 'text/javascript'); ?>
  <?php echo $this->headScript()->appendFile('/ckeditor/ckeditor.js', 'text/javascript'); ?>
  
  <?php echo $this->headLink()->appendStylesheet('/css/datetime-picker/bootstrap-datetimepicker.min.css') ?>
  <?php date_default_timezone_set('Asia/Taipei'); ?>
  <script>
    $(document).ready(function () {

        $("#editEvent").click(function(event) {
            $("#divEditEvent").show();
            $("#divEditTicket").hide();
            $("#divEditForm").hide();
        });

        function getClickID (editID) {
            var clickID;

            if ( $("div[id^='NewTicket_'][style^='display: block;'] .form_datetime_start_sales").length === 0){
                clickID = editID;
            }else{
                clickID = $("div[id^='NewTicket_'][style^='display: block;'] .form_datetime_start_sales").parent().attr('class').match(/form-group saleTimePicker-start start_sales_(\d)/)[1];
            }

            return clickID;
        }

        function dtpEndsalesUpdate (editID) {
            var clickID = getClickID(editID);

            var end_sales     = '.saleTimePicker-end.end_sales_' + clickID;
            var endSales_time = $(end_sales + ' .dtp_endSales' + clickID).val();
            var endSalesID    = '#dtp_endSales_' + clickID;
            // id = $('.table tbody tr').length + 1;

            if ($(endSalesID).length > 0) {
                // hidden value exists
                $(endSalesID).val(endSales_time);
            } else{
                $(end_sales).append('<input type="hidden" id="dtp_endSales_' + clickID + '" name="ticket[' + clickID + '][sale_end]" value="' + endSales_time + '" />');
            }
        }

        function dtpStartsalesUpdate (editID) {
            var clickID = getClickID(editID);

            var start_sales = '.saleTimePicker-start.start_sales_' + clickID;
            var end_sales   = '.saleTimePicker-end.end_sales_' + clickID;

            var startSalesID    = '#dtp_startSales_' + clickID;
            var endSalesID      = '#dtp_endSales_' + clickID;
            var startSales_time = $(start_sales + ' .dtp_startSales' + clickID).val();
            var endSales_time   = $(end_sales + ' .dtp_endSales' + clickID).val();
            var dtp_end         = '.end_sales_' + clickID + ' .form_datetime_end_sales';
            $(dtp_end).datetimepicker('setStartDate', startSales_time);

            if ($(startSalesID).length > 0) {
                // hidden value exists
                $(startSalesID).val(startSales_time);
            } else{
                $(start_sales).append('<input type="hidden" id="dtp_startSales_' + clickID + '" name="ticket[' + clickID + '][sale_start]" value="' + startSales_time + '" />');
            }

            if (startSales_time > endSales_time) {
                $(dtp_end).datetimepicker('update', startSales_time);
                if ($(endSalesID).length > 0) {
                    // hidden value exists
                    $(endSalesID).val(startSales_time);
                } else{
                    $(end_sales).append('<input type="hidden" id="dtp_endSales_' + clickID + '" name="ticket[' + clickID + '][sale_end]" value="' + startSales_time + '" />');
                }
            };
        }

        function ticketValidation (selector) {
            var clickID = selector.attr('id').match(/(\d)/)[0];
            var sale_startSel = 'input[name="' + 'ticket[' + clickID + '][sale_start]' + '"]';
            var sale_endSel   = 'input[name="' + 'ticket[' + clickID + '][sale_end]' + '"]';
            var ticketNameSel = 'input[name="' + 'ticket[' + clickID + '][ticketName]' + '"]';
            var quantitySel   = 'input[name="' + 'ticket[' + clickID + '][quantity]' + '"]';
            var priceSel      = 'input[name="' + 'ticket[' + clickID + '][price]' + '"]';

            var ticketNameVal = $(ticketNameSel).val();
            var quantityVal   = $(quantitySel).val();
            var priceVal      = $(priceSel).val();
            var sale_startVal = $(sale_startSel).val();
            var sale_endVal   = $(sale_endSel).val();

            var quantityValidate = new RegExp(/^[1-9](\d{0,3}$)/);
            var priceValidate = new RegExp(/^[1-9](\d)*/ | 0);
            var isRequired = false;

            if (!$.trim(ticketNameVal)) {
                $('.ticketName_' + clickID).attr('class', 'form-group ticketName_' + clickID + ' has-error');
                $('.ticketName_' + clickID + ' input').after('<label id="ticketName_' + clickID + '" class="control-label">請輸入票種名稱</label>');

                $('html, body').animate({
                    scrollTop: $("input[name='ticket["+ clickID +"][ticketName]']").offset().top
                }, 1000);
                isRequired = true;
            } else{
                $('.ticketName_' + clickID).attr('class', 'form-group ticketName_' + clickID);
                $('#ticketName_' + clickID).remove();
            };

            if (!$.trim(quantityVal) ||
                !quantityValidate.test(quantityVal)) {
                $('.quantity_' + clickID).attr('class', 'form-group quantity_' + clickID + ' has-error');
                $('.quantity_' + clickID + ' input').after('<label id="quantity_' + clickID + '" class="control-label">請輸入數量1~9999</label>');

                $('html, body').animate({
                    scrollTop: $("input[name='ticket["+ clickID +"][ticketName]']").offset().top
                }, 1000);
                isRequired = true;
            } else{
                $('.quantity_' + clickID).attr('class', 'form-group quantity_' + clickID);
                $('#quantity_' + clickID).remove();
            };

            if (!$.trim(priceVal) ||
                !priceValidate.test(priceVal)) {
                $('.price_' + clickID).attr('class', 'form-group price_' + clickID + ' has-error');
                $('.price_' + clickID + ' input').after('<label id="price_' + clickID + '" class="control-label">請輸入售價0元以上</label>');

                $('html, body').animate({
                    scrollTop: $("input[name='ticket["+ clickID +"][quantity]']").offset().top
                }, 1000);
                isRequired = true;
            } else{
                $('.price_' + clickID).attr('class', 'form-group price_' + clickID);
                $('#price_' + clickID).remove();
            };

            if (!$.trim(sale_startVal)) {
                $('.start_sales_' + clickID).attr('class', 'form-group saleTimePicker-start has-error start_sales_' + clickID);
                $('.start_sales_' + clickID + ' .dtp_startSales' + clickID).after('<label id="sale_start_' + clickID + '" class="control-label">請輸入開始時間</label>');
                $('.start_sales_' + clickID + ' .dtp_startSales' + clickID).focus();
                isRequired = true;
            } else{
                $('.start_sales_' + clickID).attr('class', 'form-group saleTimePicker-start start_sales_' + clickID);
                // console.log('sale_start_' + clickID);
                $('#sale_start_' + clickID).remove();
            };

            if (!$.trim(sale_endVal)) {
                $('.end_sales_' + clickID).attr('class', 'form-group saleTimePicker-end has-error end_sales_' + clickID);
                $('.end_sales_' + clickID + ' .dtp_endSales' + clickID).after('<label id="sale_end_' + clickID + '" class="control-label">請輸入開始時間</label>');
                $('.end_sales_' + clickID + ' .dtp_endSales' + clickID).focus();
                isRequired = true;
            } else{
                $('.end_sales_' + clickID).attr('class', 'form-group saleTimePicker-end end_sales_' + clickID);
                // console.log('sale_end_' + clickID);
                $('#sale_end_' + clickID).remove();
            };

            return {
                "clickID"      : clickID,
                "isRequired"   : isRequired,
                "ticketNameVal": ticketNameVal,
                "quantityVal"  : quantityVal,
                "priceVal"     : priceVal,
                "sale_startVal": sale_startVal,
                "sale_endVal"  : sale_endVal
            };            
        }

        $("#editTicket").click(function(event) {
            var activitySel    = "input[name='event[activityName]']";
            var start_timeSel  = "input[name='event[start_time]']";
            var end_timeSel    = "input[name='event[end_time]']";
            var descriptionSel = "textarea[name='event[description]']";

            var activityValue    = $(activitySel).val();
            var start_timeValue  = $(start_timeSel).val();
            var end_timeValue    = $(end_timeSel).val();
            var descriptionValue = $("#cke_editor1 iframe").contents().find("body").text();

            var isRequired = false;

            if (!$.trim(activityValue)) {
                $('.activityName').attr('class', 'form-group activityName has-error');
                $(activitySel).after('<label id="activityName" class="control-label">請輸入</label>');
                $(activitySel).focus();
                isRequired = true;
            } else{
                $('.activityName').attr('class', 'form-group activityName');
                $("#activityName").remove();
            };

            if (!$.trim(start_timeValue)) {
                $('.start_time').attr('class', 'form-group start_time has-error');
                $(start_timeSel).after('<label id="start_time" class="control-label">請輸入開始時間</label>');
                // $(start_timeSel).focus();
                $('html, body').animate({
                    scrollTop: $(activitySel).offset().top
                }, 1000);
                isRequired = true;
            } else{
                $('.start_time').attr('class', 'form-group start_time');
                $('#start_time').remove();
            };

            if (!$.trim(end_timeValue)) {
                $('.end_time').attr('class', 'form-group end_time has-error');
                $(end_timeSel).after('<label id="end_time" class="control-label">請輸入結束時間</label>');
                // $(end_timeSel).focus();
                isRequired = true;
            } else{
                $('.end_time').attr('class', 'form-group end_time');
                $('#end_time').remove();
            };

            if (!$.trim(descriptionValue)) {
                $('.description').attr('class', 'form-group description has-error');
                $(descriptionSel).after('<label id="description" class="control-label">請輸入</label>');
                // $(descriptionSel).focus();
                $('html, body').animate({
                    scrollTop: $('#event-category').offset().top
                }, 1000);
                isRequired = true;
            } else{
                $('.description').attr('class', 'form-group description');
                $("#description").remove();
            };
            
            if (!isRequired) {
                $("#divEditEvent").hide();
                $("#divEditTicket").show();
                $("#divEditForm").hide();
            };
        });

        $("#backTicket").click(function(event) {
            $("#divEditEvent").hide();
            $("#divEditTicket").show();
            $("#divEditForm").hide();
        });

        $("#editForm").click(function(event) {
            if ($(".editTable").length > 0) {
                $("#divEditEvent").hide();
                $("#divEditTicket").hide();
                $("#divEditForm").show();
                $("#newTicket").parent().attr('class', "form-group");
                $("#newTicket").next().remove();
                $('#newTicket').attr('class', 'btn btn-default');
            } else{
                $("#newTicket").parent().attr('class', "form-group has-error");
                $("#newTicket").after('<label class="control-label" for="inputError1">請至少設定一張票種</label>');
                $('#newTicket').attr('class', 'btn btn-danger');
            };
        });

        var today = new Date();
        var ii    = today.getMinutes();
        var hh    = today.getHours();
        var dd    = today.getDate();
        var mm    = today.getMonth() + 1;
        var yyyy  = today.getFullYear();

        if (ii < 10) {
            ii = '0' + ii;
        };

        if (hh < 10) {
            hh = '0' + hh;
        };

        if (dd < 10) {
            dd = '0' + dd;
        }

        if (mm < 10) {
            mm = '0' + mm;
        }

        today = yyyy + '-' + mm + '-' + dd + ' ' + hh + ':' + ii;
        
        $('.form_datetime').datetimepicker({
            language:  'zh-TW',
            weekStart: 1,
            todayBtn:  1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            forceParse: 0,
            showMeridian: 1,
            pickerPosition: "bottom-left",
            startDate: today,
            minuteStep: 30
        });

        var id;
        var editID;
        
        $('.form_datetime_dtp_input1').on('hide', function  (event) {
            var start_time = $("input[name='event[start_time]']").val();
            var end_time   = $("input[name='event[end_time]']").val();

            $('.form_datetime_dtp_input2').datetimepicker('setStartDate', start_time);
            
            if (start_time > end_time) {
                $(".form_datetime_dtp_input2").datetimepicker('update', start_time);
            };
        });

        $('.form_datetime_start_sales').on('hide', function  (event) {
            dtpStartsalesUpdate(editID);
        });

        $('.form_datetime_end_sales').on('hide', function  (event) {
            dtpEndsalesUpdate(editID);
        });

        $('#newTicket').click(function(event) {
            if( $('.table tbody tr td.editTable button:last').attr('id') === undefined) {
                id = 1;
            } else {
                // id = $('.table tbody tr td.editTable button:last').attr('id').slice(11);
                id++;
            }
            // console.log('newticket' + id);

            $("div#divEditTicket table").after('<div class="col-cg-6 bg-success" id="NewTicket_' + id +'">' + 
                '<div class="form-group ticketName_' + id + '">' + 
                    '<label class="control-label">票種</label> <input class="form-control" type="text" id="ticc" name="ticket[' + id + '][ticketName]" placeholder="例如：一般票、學生票"></div>' + 
                '<div class="form-group quantity_' + id + '">' + 
                    '<label class="control-label">數量</label> <input class="form-control" name="ticket[' + id + '][quantity]" placeholder="票種總和不可多於活動參加人數"> </div>' + 
                '<div class="form-group price_' + id + '"> <label class="control-label">售價</label> <input class="form-control" name="ticket[' + id + '][price]" placeholder="單張票價"> </div>' +
                '<span id="spanNewTicket">' +
                    '<span class="saleTimePicker" style="display:none;">' +
                        '<div class="form-group saleTimePicker-start start_sales_' + id + '">' +
                            '<label for="dtp_startSales' + id + '" class="col-md-2 control-label">販售開始時間</label>' +
                            '<div class="input-group date form_datetime form_datetime_start_sales col-md-5" data-date="" data-date-format="yyyy MM dd - p HH:ii" data-link-field="dtp_startSales' + id + '" id="Div_dtp_startSales_' + id + '">' +
                                '<input class="form-control" size="16" type="text" value="" readonly>' +
                                '<span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>' +
                                '<span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>' +
                            '</div>' +
                            '<input type="hidden" class="dtp_startSales' + id + '" id="dtp_startSales' + id + '" value="" /><br/>' +
                        '</div>' +
                        '<div class="form-group saleTimePicker-end end_sales_' + id + '">' +
                            '<label for="dtp_endSales' + id + '" class="col-md-2 control-label">販售結束時間</label>' +
                            '<div class="input-group date form_datetime form_datetime_end_sales col-md-5" data-date="" data-date-format="yyyy MM dd - p HH:ii" data-link-field="dtp_endSales' + id + '" id="Div_dtp_endSales">' +
                                '<input class="form-control" size="16" type="text" value="" readonly>' +
                                '<span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>' +
                                '<span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>' +
                            '</div>' +
                            '<input type="hidden" class="dtp_endSales' + id + '" id="dtp_endSales' + id + '" value="" /><br/>' +
                        '</div>' +
                    '</span>' +
                '</span>' +
                //'<div class="form-group"> <label>最少訂購數量</label> <select class="form-control" name="ticket[' + id + '][min_order]"> <option>1</option> <option>2</option> <option>3</option> </select> </div>' +
                '<div class="form-group"> <label>最多訂購數量</label> <select class="form-control" name="ticket[' + id + '][max_order]"> <option value="1">1</option> <option value="2">2</option> <option value="3">3</option> <option value="4">4</option> <option value="5">5</option> <option value="6">6</option> <option value="7">7</option> <option value="8">8</option> <option value="9">9</option> <option value="10">10</option> </select> </div>' +
                
                <?php if (!isset($this->event['url'])): ?>
                '<button class="btn btn-default AddTicket" id="AddTicket_' + id + '" type="button" class="btn btn-default">新增</button>' +
                <?php endif ?>
                
                '<button class="btn btn-default SaveTicket" id="SaveTicket_' + id + '" type="button" style="display:none;" class="btn btn-default">存檔</button>' +

                <?php if (!isset($this->event['url'])): ?>
                '<button class="btn btn-default DeleteTicket" id="DeleteTicket_' + id + '" type="button" style="display:none;" class="btn btn-default">刪除</button>' + 
                '<button class="btn btn-default CancelTicket" id="CancelTicket_' + id + '" type="button" class="btn btn-default">取消</button>' +
                <?php endif ?>

                '</div>'
            );
            // initialize new datetimepicker
            $('.form_datetime').datetimepicker({
                language:  'zh-TW',
                weekStart: 1,
                todayBtn:  1,
                autoclose: 1,
                todayHighlight: 1,
                startView: 2,
                forceParse: 0,
                showMeridian: 1,
                pickerPosition: "bottom-left",
                startDate: today,
                minuteStep: 30
            });

            var dom = '.saleTimePicker_' + id;
            $(".saleTimePicker").appendTo(dom);
            $(".saleTimePicker").show();
            $("#newTicket").attr('disabled', true);
            $(".editTable button").attr('disabled', true);

            $('.form_datetime_start_sales').on('hide', function  (event) {
                dtpStartsalesUpdate(id);
            });

            $('.form_datetime_end_sales').on('hide', function  (event) {
                dtpEndsalesUpdate(id);
            });
        });
        
        // AddTicket event
        $('div#divEditTicket').on("click", 'button.AddTicket', function(){
            var ticketVal = ticketValidation($(this));

            if (!ticketVal.isRequired) {
                $('.table-bordered#ticketTable tbody').append('<tr class="ID_' + ticketVal.clickID + '">' +
                                                    '<td>' + ticketVal.ticketNameVal + '</td>' +
                                                    '<td>' + ticketVal.sale_startVal + '~' + ticketVal.sale_endVal + '</td>' +
                                                    '<td>' + ticketVal.priceVal + '</td>' +
                                                    '<td>' + ticketVal.quantityVal + '</td>' +
                                                    '<td class="editTable"><button type="button" class="btn btn-default" id="editTicket_' + ticketVal.clickID +'">編輯</button></td>' +
                                                '</tr>'
                );

                $("#newTicket").attr('disabled', false);
                $(".editTable button").attr('disabled', false);
                // $("#SaveTicket_" + clickID).show();
                // $("#AddTicket_" + clickID).hide();
                $("#NewTicket_" + ticketVal.clickID).hide();
            };
        });
        
        // CancelTicket event
        $('div#divEditTicket').on("click", 'button.CancelTicket', function(){
            var clickID = $(this).attr('id');
            clickID = clickID.slice(13);
            // console.log('class="CancelTicket:' + clickID);
            $('#NewTicket_' + clickID).remove();
            $("#newTicket").attr('disabled', false);
            $(".editTable button").attr('disabled', false);

            id--;
        });

        // editTicket event
        $('.table-bordered#ticketTable tbody').on('click', '.editTable button', function(event) {
            var clickID = $(this).attr('id');
            clickID = clickID.slice(11);
            editID = clickID;
            // console.log('editTable:' + clickID);
            event.preventDefault();
            $("#AddTicket_" + clickID).hide();
            $("#SaveTicket_" + clickID).show();
            $("#DeleteTicket_" + clickID).show();
            $("#CancelTicket_" + clickID).hide();
            $('#NewTicket_' + clickID).show();
            $("#newTicket").attr('disabled', true);
            $(".editTable button").attr('disabled', true);
        });

        // SaveTicket event
        $('div#divEditTicket').on('click', 'button.SaveTicket', function(event) {
            var ticketVal = ticketValidation($(this));

            if (!ticketVal.isRequired) {
                $('#NewTicket_' + ticketVal.clickID).hide();

                $('tr.ID_' + ticketVal.clickID).html('<td>' + ticketVal.ticketNameVal + '</td>' +
                                            '<td>' + ticketVal.sale_startVal + '~' + ticketVal.sale_endVal + '</td>' +
                                            '<td>' + ticketVal.priceVal + '</td>' +
                                            '<td>' + ticketVal.quantityVal + '</td>' +
                                            '<td class="editTable"><button type="button" class="btn btn-default" id="editTicket_' + ticketVal.clickID +'">編輯</button></td>'
                                        );
                $("#newTicket").attr('disabled', false);
                $(".editTable button").attr('disabled', false);
            };
        });

        // DeleteTicket event
        $('div#divEditTicket').on('click', 'button.DeleteTicket', function(event) {
            var clickID = $(this).attr('id');
            clickID = clickID.slice(13);
            // console.log('DeleteTicket:' + clickID);
            $('#NewTicket_' + clickID).remove();
            $('.ID_' + clickID).remove();
            $("#newTicket").attr('disabled', false);
            $(".editTable button").attr('disabled', false);
        });

        //  this function is used for detecting table's row number.
        // var numberOfRows = $("div#divEditTicket .table-bordered>tbody>tr").length;
        // console.log(numberOfRows);
        // $("div#divEditTicket .table-bordered>tbody").bind("DOMSubtreeModified", function() {
        //     if($("div#divEditTicket .table-bordered>tbody>tr").length !== numberOfRows){
        //         numberOfRows = $("div#divEditTicket .table-bordered>tbody>tr").length;
        //         console.log('numberOfRows:' + numberOfRows);
        //     }
        // });
    });
    
    function PreviewImage() {
        var oFReader = new FileReader();
        oFReader.readAsDataURL(document.getElementById("uploadImage").files[0]);

        oFReader.onload = function (oFREvent) {
            document.getElementById("uploadPreview").src = oFREvent.target.result;
        };
    };
    </script>
        <form action="<?php echo $this->formActionUrl($this->action, 'event', null, $this->params) ?>" class="form-signin" enctype="multipart/form-data" role="form" method="post">
            <div class="container">
                <div class="row" id="divEditEvent">
                    <div class="col-cg-6">
                    <h1>建立活動</h1>
                        <div class="form-group activityName">
                            <label class="control-label"><strong>*</strong>活動名稱</label>
                            <input required class="form-control" name="event[activityName]" value="<?php echo @$this->event['name'] ?>">
                        </div>
                        <div class="form-group start_time">
                            <label for="dtp_input1" class="col-md-2 control-label"><strong>*</strong>活動開始時間</label>
                            <div class="input-group date form_datetime form_datetime_dtp_input1 col-md-5" data-date-format="yyyy MM dd - p HH:ii" data-link-field="dtp_input1">
                                <input class="form-control" size="16" type="text" value="<?php echo @$this->event['start_time'] ?> " readonly>
                                <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                                <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                            </div>
                            <input type="hidden" id="dtp_input1" value="<?php echo @$this->event['start_time'] ?> " name="event[start_time]" /><br/>
                        </div>
                        <div class="form-group end_time">
                            <label for="dtp_input2" class="col-md-2 control-label"><strong>*</strong>活動結束時間</label>
                            <div class="input-group date form_datetime form_datetime_dtp_input2 col-md-5" data-date-format="yyyy MM dd - p HH:ii" data-link-field="dtp_input2">
                                <input class="form-control" size="16" type="text" value="<?php echo @$this->event['end_time'] ?> " readonly>
                                <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                                <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                            </div>
                            <input type="hidden" id="dtp_input2" value="<?php echo @$this->event['end_time'] ?> " name="event[end_time]" /><br/>
                        </div>
                        <div class="form-group">
                            <label>活動地點</label>
                            <?php echo $this->formSelect('event[site]',
                                                            @$this->event['site'],
                                                            array('class' => 'form-control'),
                                                            array(
                                                                1 => '新生命教會',
                                                                2 => '新莊',
                                                                3 => '其他'
                                                            )
                                                )
                            ?>
                        </div>
                        <div class="form-group">
                            <label>教室</label>
                            <?php $classroomKey = Zend_Registry::get('classroomKey'); ?>
                            <?php echo $this->formSelect('event[classroom]',
                                                            @$this->event['classroom'],
                                                            array('class' => 'form-control input-small'),
                                                           $classroomKey
                                                )
                            ?>
                        </div>
                        <div class="form-group form-inline">
                            <label class="control-label">縣市</label>
                            <?php $CountyKey = Zend_Registry::get('CountyKey'); ?>
                            <?php echo $this->formSelect('event[county]',
                                                            @$this->event['county'],
                                                            array('class' => 'form-control input-small'),
                                                           $CountyKey
                                                )
                            ?>
                            <!-- <label>地址</label> -->
                            <input class="form-control" name="event[address]" value="<?php echo @$this->event['address'] ?>">
                        </div>
                        <div class="form-group">
                            <label>主辦人</label>
                            <input class="form-control" name="event[host]" value="<?php echo @$this->event['host'] ?>">
                        </div>
                        <!-- <div class="form-group">
                            <label><strong>*</strong>活動人數</label>
                            <input required class="form-control" name="event[capacity]" value="<?php //echo @$this->event['capacity'] ?>">
                        </div> -->
                        <div class="form-group">
                            <label>活動分類</label>
                            <?php $categoryKey = Zend_Registry::get('categoryKey'); ?>
                            <?php echo $this->formSelect('event[category]',
                                                            @$this->event['category'],
                                                            array('class' => 'form-control input-small'),
                                                           $categoryKey
                                                )
                            ?>
                        </div>
                        <div class="form-group description">
                            <label class="control-label"><strong>*</strong>活動描述</label>
                            <textarea required class="ckeditor form-control" cols="80" id="editor1" name="event[description]" rows="10"><?php echo @$this->event['description'] ?> </textarea>    
                        </div>
                        <div class="form-group">
                            <label>是否公開活動</label>
                            <?php $privacyKey = Zend_Registry::get('privacyKey'); ?>
                            <?php echo $this->formRadio('event[privacy]',
                                                            isset($this->event['privacy']) ? $this->event['privacy'] : '1',
                                                            array('label_class' => 'radio-inline'),
                                                           $privacyKey,
                                                           '<span></span>'
                                                )
                            ?>
                        </div>
                        <div class="form-group">
                            <dl>
                              <dt>活動分享圖片
                              </dt>
                              <dd>
                                <ol>
                                    <li>上傳的格式包含 JPEG、PNG、GIF</li>
                                    <li>上傳最大檔案容量為2.5MB。</li>
                                    <li>如果沒有上傳或是上傳失敗，會使用系統預設圖片。</li>
                                </ol>
                              </dd>
                            </dl>
                            <img src="<?php echo isset($this->event['image']) ? 
                                                        '/img/' . $this->event['image'] :
                                                         'http://placehold.it/300x300' ?>" 
                             class="img-responsive" id="uploadPreview">
                            <span class="btn btn-default btn-file" style="position: relative; overflow: hidden; ">
                                選擇圖片上傳
                                <input type="file" id="uploadImage" name="upload" onchange="PreviewImage();" style="position: absolute; top: 0; right: 0; min-width: 100%; min-height: 100%; font-size: 999px; text-align: right; filter: alpha(opacity=0); opacity: 0; outline: none; background: white; cursor: inherit; display: block;">
                            </span>
                        </div>
                        <button type="button" class="btn btn-default" disabled="disabled">上一步</button>
                        <button id="editTicket" type="button" class="btn btn-default">下一步</button>
                    </div>
                </div>
                
                <div class="row" id="divEditTicket" style="display:none;">
                    <table class="table table-bordered" id="ticketTable">
                      <thead>
                        <tr>
                          <th>票種</th>
                          <th>販售時間</th>
                          <th>價格</th>
                          <th>數量</th>
                          <th>編輯</th>
                        </tr>
                      </thead>
                      <tbody>
                        <?php if (isset($this->tickets)): ?>
                            <?php foreach ($this->tickets as $key => $ticket): ?>
                            <tr class="<?php echo 'ID_' . $ticket['ticket_id'] ?> ">
                                <td><?php echo $ticket['ticketName'] ?></td>
                                <td><?php echo $ticket['sale_start'] . '~' . $ticket['sale_end'] ?></td>
                                <td><?php echo $ticket['price'] ?></td>
                                <td><?php echo $ticket['quantity'] ?></td>
                                <td class="editTable"><button type="button" class="btn btn-default" id="<?php echo 'editTicket_' . $ticket['ticket_id'] ?>">編輯</button></td>
                            </tr>
                            <?php endforeach ?>
                        <?php endif ?>
                      </tbody>
                    </table>
                    <?php if (isset($this->tickets)): ?>
                        <?php foreach ($this->tickets as $key => $ticket): ?>
                            <div class="col-cg-6 bg-success" id="<?php echo 'NewTicket_' . $ticket['ticket_id'] ?>" style="display:none;">
                                <div class="form-group ticketName_<?php echo $ticket['ticket_id'] ?>">
                                    <label class="control-label">票種</label> <input class="form-control" type="text" name="ticket[<?php echo $ticket['ticket_id']  ?>][ticketName]" placeholder="例如：一般票、學生票" value="<?php echo $ticket['ticketName'] ?>"></div>
                                <div class="form-group quantity_<?php echo $ticket['ticket_id'] ?>">
                                    <label class="control-label">數量</label> <input class="form-control" name="ticket[<?php echo $ticket['ticket_id']  ?>][quantity]" placeholder="票種總和不可多於活動參加人數" value="<?php echo $ticket['quantity'] ?>"> </div>
                                <div class="form-group price_<?php echo $ticket['ticket_id'] ?>"> <label class="control-label">售價</label> <input class="form-control" name="ticket[<?php echo $ticket['ticket_id']  ?>][price]" placeholder="單張票價" value="<?php echo $ticket['price'] ?>"> </div>
                                <span id="spanNewTicket">
                                    <span class="saleTimePicker" style="">
                                        <div class="form-group saleTimePicker-start start_sales_<?php echo $ticket['ticket_id'] ?>">
                                            <label for="dtp_startSales<?php echo $ticket['ticket_id'] ?>" class="col-md-2 control-label">販售開始時間</label>
                                            <div class="input-group date form_datetime form_datetime_start_sales col-md-5" data-date="" data-date-format="yyyy MM dd - p HH:ii" data-link-field="dtp_startSales<?php echo $ticket['ticket_id'] ?>" id="Div_dtp_startSales_<?php echo $ticket['ticket_id'] ?>">
                                                <input class="form-control" size="16" type="text" value="<?php echo $ticket['sale_start'] ?>" readonly>
                                                <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                                                <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                                            </div>
                                            <input type="hidden" class="dtp_startSales<?php echo $ticket['ticket_id'] ?>" id="dtp_startSales<?php echo $ticket['ticket_id'] ?>" value="<?php echo $ticket['sale_start'] ?>" /><br/>
                                            <input type="hidden" id="dtp_startSales_<?php echo $ticket['ticket_id']  ?>" name="ticket[<?php echo $ticket['ticket_id']  ?>][sale_start]" value="<?php echo $ticket['sale_start'] ?>" />
                                        </div>
                                        <div class="form-group saleTimePicker-end end_sales_<?php echo $ticket['ticket_id'] ?>">
                                            <label for="dtp_endSales<?php echo $ticket['ticket_id'] ?>" class="col-md-2 control-label">販售結束時間</label>
                                            <div class="input-group date form_datetime form_datetime_end_sales col-md-5" data-date="" data-date-format="yyyy MM dd - p HH:ii" data-link-field="dtp_endSales<?php echo $ticket['ticket_id'] ?>" id="Div_dtp_endSales_<?php echo $ticket['ticket_id'] ?>">
                                                <input class="form-control" size="16" type="text" value="<?php echo $ticket['sale_end'] ?>" readonly>
                                                <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                                                <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                                            </div>
                                            <input type="hidden" class="dtp_endSales<?php echo $ticket['ticket_id'] ?>" id="dtp_endSales<?php echo $ticket['ticket_id'] ?>" value="<?php echo $ticket['sale_end'] ?>" /><br/>
                                            <input type="hidden" id="dtp_endSales_<?php echo $ticket['ticket_id']  ?>" name="ticket[<?php echo $ticket['ticket_id']  ?>][sale_end]" value="<?php echo $ticket['sale_end'] ?>" />
                                        </div>
                                    </span>
                                </span>
                                    
                                <!-- <div class="form-group"> <label>最少訂購數量</label> <select class="form-control" name="ticket[<?php //echo $ticket['ticket_id']  ?>][min_order]"> <option>1</option> <option>2</option> <option>3</option> </select> </div> -->
                                <div class="form-group"> 
                                    <label>最多訂購數量</label>
                                    <?php echo $this->formSelect('ticket[' . $ticket['ticket_id'] . '][max_order]',
                                                            @$ticket['max_order'],
                                                            array('class' => 'form-control'),
                                                            array(
                                                                1 => '1',
                                                                2 => '2',
                                                                3 => '3',
                                                                4 => '4',                                                                
                                                                5 => '5',
                                                                6 => '6',
                                                                7 => '7',
                                                                8 => '8',
                                                                9 => '9',
                                                                10 => '10',
                                                            )
                                                )
                                    ?>
                                </div>
                                <button class="btn btn-default SaveTicket" id="SaveTicket_<?php echo $ticket['ticket_id']  ?>" type="button" style="" class="btn btn-default">存檔</button>
                            </div>
                        <?php endforeach ?>    
                    <?php endif ?>
                    <?php /* after establishing events, tickets could not be added */ ?>
                    <?php if (!isset($this->event['url'])): ?>
                        <div class="form-group">
                            <button id="newTicket" type="button" class="btn btn-default">新增票種</button>
                        </div>
                    <?php endif ?>
                    <button id="editEvent" type="button" class="btn btn-default">上一步</button>
                    <button id="editForm" type="button" class="btn btn-default">下一步</button>
                </div>
                <div class="row" id="divEditForm" style="display:none;">
                    <h1>設定表單</h1>
                    <div class="col-cg-6">
                    <table class="table table-bordered">
                        <tr>
                            <th>必填</th>
                            <th>欄位</th>
                            <th>範例表格</th>
                        </tr>
                        <tbody>
                        <?php foreach ($this->forms as $data): ?>
                            <tr>
                                <td>
                                    <div class="form-group checkbox">
                                        <label>
                                            <?php echo $this->formCheckbox('form[' . $data['name'] . ']',
                                                                                                     null,
                                                                                                      array('checked' => isset($this->required) ? $this->required[$data['name']] : '0'
                                                                                                    )
                                              ) ?>
                                        </label>
                                    </div>
                                </td>
                                <td>
                                    <?php echo $data['formName'] ?>
                                </td>
                                <td>
                                    <div class="form-group">
                                        <?php echo $this->formText('xxx', null, array('class' => 'form-control', 'placeholder' => $data['placeholder'])) ?>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach ?>
                            <tr>
                                <td>
                                    <div class="form-group checkbox">
                                        <label>
                                            <?php echo $this->formCheckbox('form[birthday]', null, array('checked' => isset($this->required) ? $this->required['birthday'] : '0')) ?>
                                        </label>
                                    </div>
                                </td>
                                <td>
                                    生日
                                </td>
                                <td>
                                    <div class="form-group form-inline">
                                        <label class="control-label">西元</label>
                                        <input class="form-control" placeholder="19xx">
                                        <label class="control-label">年</label>
                                        <input class="form-control" placeholder="8">
                                        <label class="control-label">月</label>
                                        <input class="form-control" placeholder="20">
                                        <label class="control-label">日</label>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="form-group checkbox">
                                        <label>
                                            <?php echo $this->formCheckbox('form[gender]', null, array('checked' => isset($this->required) ? $this->required['gender'] : '0')) ?>
                                        </label>
                                    </div>
                                </td>
                                <td>
                                    性別
                                </td>
                                <td>
                                    <div class="form-group">
                                        <?php echo $this->formSelect('xxx', 1, array('class' => 'form-control'), array(1 => '--', 2 => '男', 3 =>'女')) ?>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="form-group checkbox">
                                        <label>
                                            <?php echo $this->formCheckbox('form[group]', null, array('checked' => isset($this->required) ? $this->required['group'] : '0')) ?>
                                        </label>
                                    </div>
                                </td>
                                <td>
                                    牧區
                                </td>
                                <td>
                                    <div class="form-group">
                                        <?php echo $this->formSelect('xxx', 0, array('class' => 'form-control'), $this->groups) ?>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="form-group checkbox">
                                        <label>
                                            <?php echo $this->formCheckbox('form[food]', null, array('checked' => isset($this->required) ? $this->required['food'] : '0')) ?>
                                        </label>
                                    </div>
                                </td>
                                <td>
                                    飲食
                                </td>
                                <td>
                                    <div class="form-group">
                                        <?php echo $this->formSelect('xxx', 1, array('class' => 'form-control'), array(1 => '--', 2 => '葷食', 3 =>'素食', 4 => '不訂便當')) ?>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="form-group checkbox">
                                        <label>
                                            <?php echo $this->formCheckbox('form[other]', null, array('checked' => isset($this->required) ? $this->required['other'] : '0')) ?>
                                        </label>
                                    </div>
                                </td>
                                <td>
                                    其他事項
                                </td>
                                <td>
                                    <div class="form-group">
                                        <textarea cols="80" class="form-control" rows="10"></textarea>   
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                        <button id="backTicket" type="button" class="btn btn-default">上一步</button>
                        <button id="submit" type="submit" class="btn btn-default">完成</button>
                    </div>
                </div>
            </div>
        </form>