<script src="//code.jquery.com/jquery-1.9.1.js"></script>
  <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
  
  <?php echo $this->headScript()->appendFile('/js/datetime-picker/bootstrap-datetimepicker.min.js', 'text/javascript'); ?>
  <?php echo $this->headScript()->appendFile('/js/datetime-picker/locales/bootstrap-datetimepicker.zh-TW.js', 'text/javascript'); ?>
  <?php echo $this->headScript()->appendFile('/ckeditor/ckeditor.js', 'text/javascript'); ?>
  
  <?php echo $this->headLink()->appendStylesheet('/css/datetime-picker/bootstrap-datetimepicker.min.css') ?>
  <script>
    $(document).ready(function () {

        $("#editEvent").click(function(event) {
            $("#divEditEvent").show();
            $("#divEditTicket").hide();
            $("#divEditForm").hide();
        });

        $("#editTicket").click(function(event) {
            $("#divEditEvent").hide();
            $("#divEditTicket").show();
            $("#divEditForm").hide();
        });

        $("#backTicket").click(function(event) {
            $("#divEditEvent").hide();
            $("#divEditTicket").show();
            $("#divEditForm").hide();
        });

        $("#editForm").click(function(event) {
            $("#divEditEvent").hide();
            $("#divEditTicket").hide();
            $("#divEditForm").show();
        });

        var today = new Date();
        var ii    = today.getMinutes();
        var hh    = today.getHours();
        var dd    = today.getDate();
        var mm    = today.getMonth() + 1;
        var yyyy  = today.getFullYear();

        if (ii < 10) {
            ii = '0' + ii;
        };

        if (hh < 10) {
            hh = '0' + hh;
        };

        if (dd < 10) {
            dd = '0' + dd;
        }

        if (mm < 10) {
            mm = '0' + mm;
        }

        today = yyyy + '-' + mm + '-' + dd + ' ' + hh + ':' + ii;
        
        $('.form_datetime').datetimepicker({
            language:  'zh-TW',
            weekStart: 1,
            todayBtn:  1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            forceParse: 0,
            showMeridian: 1,
            pickerPosition: "bottom-left",
            startDate: today,
            minuteStep: 30
        });

        var id;
            
        $('.form_datetime_start_sales').on('hide', function  (event) {
            var startSalesValue = $('.dtp_startSales').val();
            var startSalesID = '#dtp_startSales_' + id;
            // id = $('.table tbody tr').length + 1;

            if ($(startSalesID).length > 0) {
                // hidden value exists
                $(startSalesID).val(startSalesValue);
            } else{
                $(".saleTimePicker-start").append('<input type="hidden" id="dtp_startSales_' + id + '" name="ticket[' + id + '][sale_start]" value="' + startSalesValue + '" />');
            }
        });

        $('.form_datetime_end_sales').on('hide', function  (event) {
            var endSalesValue = $('.dtp_endSales').val();
            var endSalesID = '#dtp_endSales_' + id;
            // id = $('.table tbody tr').length + 1;

            if ($(endSalesID).length > 0) {
                // hidden value exists
                $(endSalesID).val(endSalesValue);
            } else{
                $(".saleTimePicker-end").append('<input type="hidden" id="dtp_endSales_' + id + '" name="ticket[' + id + '][sale_end]" value="' + endSalesValue + '" />');
            }
        });

        $('#newTicket').click(function(event) {

            if( $('.table tbody tr td.editTable button:last').attr('id') === undefined) {
                id = 1;
            } else {
                // id = $('.table tbody tr td.editTable button:last').attr('id').slice(11);
                id++;
            }
            console.log('newticket' + id);

            $("div#divEditTicket #spanNewTicket").append('<div class="col-cg-6 bg-success" id="NewTicket_' + id +'">' + 
                '<div class="form-group">' + 
                    '<label>票種</label> <input class="form-control" type="text" id="ticc" name="ticket[' + id + '][ticketName]" placeholder="例如：一般票、學生票"></div>' + 
                '<div class="form-group">' + 
                    '<label>數量</label> <input class="form-control" name="ticket[' + id + '][quantity]" placeholder="票種總和不可多於活動參加人數"> </div>' + 
                '<div class="form-group"> <label>售價</label> <input class="form-control" name="ticket[' + id + '][price]" placeholder="單張票價"> </div>' +
                '<span class="saleTimePicker_' + id + '"></span>' +
                '<div class="form-group"> <label>最少訂購數量</label> <select class="form-control" name="ticket[' + id + '][min_order]"> <option>1</option> <option>2</option> <option>3</option> </select> </div>' +
                '<div class="form-group"> <label>最多訂購數量</label> <select class="form-control" name="ticket[' + id + '][max_order]"> <option>1</option> <option>2</option> <option>3</option> </select> </div>' +
                '<button class="btn btn-default AddTicket" id="AddTicket_' + id + '" type="button" class="btn btn-default">新增</button>' +
                '<button class="btn btn-default SaveTicket" id="SaveTicket_' + id + '" type="button" style="display:none;" class="btn btn-default">存檔</button>' + 
                '<button class="btn btn-default DeleteTicket" id="DeleteTicket_' + id + '" type="button" style="display:none;" class="btn btn-default">刪除</button>' + 
                '<button class="btn btn-default CancelTicket" id="CancelTicket_' + id + '" type="button" class="btn btn-default">取消</button> </div>'
            );
                
            var dom = '.saleTimePicker_' + id;
            $(".saleTimePicker").appendTo(dom);
            $(".saleTimePicker").show();
            $("#newTicket").attr('disabled', true);
            $(".editTable button").attr('disabled', true);


        });
        
        // AddTicket event
        $('div#divEditTicket #spanNewTicket').on("click", 'button.AddTicket', function(){
            var clickID = $(this).attr('id');
            clickID = clickID.slice(10);
            var ticketName = $('input[name="' + 'ticket[' + clickID + '][ticketName]' + '"]').val();
            var quantity   = $('input[name="' + 'ticket[' + clickID + '][quantity]' + '"]').val();
            var price      = $('input[name="' + 'ticket[' + clickID + '][price]' + '"]').val();
            var sale_start = $('input[name="' + 'ticket[' + clickID + '][sale_start]' + '"]').val();
            var sale_end   = $('input[name="' + 'ticket[' + clickID + '][sale_end]' + '"]').val();
            // var min_order  = $('input[name="' + 'ticket[' + clickID + '][min_order]' + '"]').val();
            // var max_order  = $('input[name="' + 'ticket[' + clickID + '][max_order]' + '"]').val();

            $('.table-bordered#ticketTable tbody').append('<tr>' +
                                                    '<td>' + ticketName + '</td>' +
                                                    '<td>' + sale_start + '~' + sale_end + '</td>' +
                                                    '<td>' + price + '</td>' +
                                                    '<td>' + quantity + '</td>' +
                                                    '<td class="editTable"><button type="button" class="btn btn-default" id="editTicket_' + clickID +'">編輯</button></td>' +
                                                '</tr>'
            );

            $("#newTicket").attr('disabled', false);
            $(".editTable button").attr('disabled', false);
            // $("#SaveTicket_" + clickID).show();
            // $("#AddTicket_" + clickID).hide();
            $("#NewTicket_" + clickID).hide();
        });
        
        // CancelTicket event
        $('div#divEditTicket #spanNewTicket').on("click", 'button.CancelTicket', function(){
            var clickID = $(this).attr('id');
            clickID = clickID.slice(13);
            // console.log('class="CancelTicket:' + clickID);
            $('#NewTicket_' + clickID).remove();
            $("#newTicket").attr('disabled', false);
            $(".editTable button").attr('disabled', false);

            id--;
        });

        // editTicket event
        $('.table-bordered#ticketTable tbody').on('click', '.editTable button', function(event) {
            var clickID = $(this).attr('id');
            clickID = clickID.slice(11);
            console.log('editTable:' + clickID);
            event.preventDefault();
            $("#AddTicket_" + clickID).hide();
            $("#SaveTicket_" + clickID).show();
            $("#DeleteTicket_" + clickID).show();
            $("#CancelTicket_" + clickID).hide();
            $('#NewTicket_' + clickID).show();
            $("#newTicket").attr('disabled', true);
            $(".editTable button").attr('disabled', true);
        });

        // SaveTicket event
        $('div#divEditTicket #spanNewTicket').on('click', 'button.SaveTicket', function(event) {
            var clickID = $(this).attr('id');

            clickID = clickID.slice(11);
            $('#NewTicket_' + clickID).hide();
            $("#newTicket").attr('disabled', false);
            $(".editTable button").attr('disabled', false);
        });

        // DeleteTicket event
        $('div#divEditTicket #spanNewTicket').on('click', 'button.DeleteTicket', function(event) {
            var clickID = $(this).attr('id');
            clickID = clickID.slice(13);
            console.log('DeleteTicket:' + clickID);
            $('#NewTicket_' + clickID).remove();
            $("#newTicket").attr('disabled', false);
            $(".editTable button").attr('disabled', false);
        });

        var numberOfRows = $("div#divEditTicket .table-bordered>tbody>tr").length;
        console.log(numberOfRows);
        $("div#divEditTicket .table-bordered>tbody").bind("DOMSubtreeModified", function() {
            if($("div#divEditTicket .table-bordered>tbody>tr").length !== numberOfRows){
                numberOfRows = $("div#divEditTicket .table-bordered>tbody>tr").length;
                console.log('numberOfRows:' + numberOfRows);
            }
        });

        
    });
    
    function PreviewImage() {
        var oFReader = new FileReader();
        oFReader.readAsDataURL(document.getElementById("uploadImage").files[0]);

        oFReader.onload = function (oFREvent) {
            document.getElementById("uploadPreview").src = oFREvent.target.result;
        };
    };
    </script>
        <form action="<?php echo $this->url(array('module' => 'administration','controller'=>'event','action'=>'create'), null, FALSE); ?>" class="form-signin" enctype="multipart/form-data" role="form" method="post">
            <div class="container">
                <div class="row" id="divEditEvent">
                    <div class="col-cg-6">
                    <h1>建立活動</h1>
                        <div class="form-group">
                            <label>活動名稱</label>
                            <input class="form-control" name="event[activityName]">
                        </div>
                        <!-- http://jqueryui.com/datepicker/ -->
                        <!-- <div><p>Date: <input type="text" id="datepicker"></p><p>Date: <input type="text" id="datepicker"></p></div> -->
                        <!-- <div class="form-group">
                         -->    
                         <!-- <div class="input-daterange" id="datepicker" >活動時間 -->
                            <!-- http://runnable.com/UmOmQbKV4wpoAAGa/bootstrap-datepicker-example-date-range-from-to-with-%22today%22-button-activated2 -->
                        
                               <!--  <input type="text" class="input-small" name="start" />
                                <span>~</span>
                                <input type="text" class="input-small" name="end" />
                            </div>
                        </div> -->
                        <div class="form-group">
                            <label for="dtp_input1" class="col-md-2 control-label">活動開始時間</label>
                            <div class="input-group date form_datetime col-md-5" data-date="<?php date_default_timezone_set('America/Los_Angeles'); echo date('Y-m-d'); ?>" data-date-format="yyyy MM dd - p HH:ii" data-link-field="dtp_input1">
                                <input class="form-control" size="16" type="text" value="" readonly>
                                <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                                <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                            </div>
                            <input type="hidden" id="dtp_input1" value="" name="event[start_time]" /><br/>
                        </div>
                        <div class="form-group">
                            <label for="dtp_input2" class="col-md-2 control-label">活動結束時間</label>
                            <div class="input-group date form_datetime col-md-5" data-date="1979-09-16T05:25:07Z" data-date-format="yyyy MM dd - p HH:ii" data-link-field="dtp_input2">
                                <input class="form-control" size="16" type="text" value="" readonly>
                                <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                                <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                            </div>
                            <input type="hidden" id="dtp_input2" value="" name="event[end_time]" /><br/>
                        </div>
                        <!-- <div class="form-group">
                            <label for="dtp_input1" class="col-md-2 control-label">活動結束時間</label>
                            <div class="input-group date form_datetime col-md-5" data-date="1979-09-16T05:25:07Z" data-date-format="dd MM yyyy - HH:ii p" data-link-field="dtp_input1">
                                <input class="form-control" size="16" type="text" value="" readonly>
                                <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                                <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                            </div>
                            <input type="hidden" id="dtp_input1" value="" name="end_time" /><br/>
                        </div> -->
                        <div class="form-group">
                            <label>活動地點</label>
                            <select class="form-control" name="event[site]">
                                <option value="1">新生命教會</option>
                                <option value="2">新莊</option>
                                <option value="3">其他</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>教室</label>
                            <select class="form-control input-small" name="event[classroom]">
                                <option value="1">第一教室</option>
                                <option value="2">弟一區塊</option>
                                <option value="3">其他</option>
                            </select>
                        </div>
                        <div class="form-group form-inline">
                            <label class="control-label">縣市</label>
                            <select class="form-control input-small" name="event[county]">
                                <option value="1">台北</option>
                                <option value="2">台南</option>
                                <option value="3">臺中</option>
                            </select>
                            <!-- <label>地址</label> -->
                            <input class="form-control" name="event[address]" placeholder="士林區仁愛路34號">
                        </div>
                        <div class="form-group">
                            <label>主辦人</label>
                            <input class="form-control" name="event[host]">
                        </div>
                        
                        <div class="form-group">
                            <label>活動人數</label>
                            <input class="form-control" name="event[capacity]">
                        </div>
                        <div class="form-group">
                            <label>活動分類</label>
                            <select class="form-control input-small" name="event[category]">
                                <option value="1">娛樂</option>
                                <option value="2">職場</option>
                                <option value="3">生活</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>活動描述</label>
                            <textarea class="ckeditor" cols="80" id="editor1" name="event[description]" rows="10"></textarea>    
                        </div>
                        <div class="form-group">
                            <label>是否公開活動</label>
                            <label class="radio-inline">
                                <input type="radio" name="event[public]" id="optionsRadiosInline1" value="1" checked="">公開
                            </label>
                            <label class="radio-inline">
                                <input type="radio" name="event[public]" id="optionsRadiosInline2" value="2">不公開
                            </label>
                        </div>
                        <div class="form-group">
                            <label>url</label>
                            <input class="form-control" name="event[url]">
                        </div>
                        <div class="form-group">
                            <label>活動分享圖片</label>
                            <img src="http://placehold.it/200x200" class="img-responsive" id="uploadPreview">
                            <span class="btn btn-default btn-file" style="position: relative; overflow: hidden; ">
                                選擇圖片上傳
                                <input type="file" id="uploadImage" name="upload" onchange="PreviewImage();" style="position: absolute; top: 0; right: 0; min-width: 100%; min-height: 100%; font-size: 999px; text-align: right; filter: alpha(opacity=0); opacity: 0; outline: none; background: white; cursor: inherit; display: block;">
                            </span>
                        </div>
                        <button type="button" class="btn btn-default" disabled="disabled">上一步</button>
                        <button id="editTicket" type="button" class="btn btn-default">下一步</button>
                    </div>
                </div>
                
                <div class="row" id="divEditTicket" style="display:none;">
                    <table class="table table-bordered" id="ticketTable">
                      <thead>
                        <tr>
                          <th>票種</th>
                          <th>販售時間</th>
                          <th>價格</th>
                          <th>數量</th>
                          <th>編輯</th>
                        </tr>
                      </thead>
                      <tbody>
                        
                      </tbody>
                    </table>
                    <span id="spanNewTicket">
                        <span class="saleTimePicker" style="display:none;">
                            <div class="form-group saleTimePicker-start">
                                <label for="dtp_startSales" class="col-md-2 control-label">販售開始時間</label>
                                <div class="input-group date form_datetime form_datetime_start_sales col-md-5" data-date="1979-09-16T05:25:07Z" data-date-format="yyyy MM dd - p HH:ii" data-link-field="dtp_startSales" id="Div_dtp_startSales">
                                    <input class="form-control" size="16" type="text" value="" readonly>
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                                </div>
                                <input type="hidden" class="dtp_startSales" id="dtp_startSales" value="" /><br/>
                            </div>
                                                    
                            <div class="form-group saleTimePicker-end">
                                <label for="dtp_endSales" class="col-md-2 control-label">販售結束時間</label>
                                <div class="input-group date form_datetime form_datetime_end_sales col-md-5" data-date="1979-09-16T05:25:07Z" data-date-format="yyyy MM dd - p HH:ii" data-link-field="dtp_endSales" id="Div_dtp_endSales">
                                    <input class="form-control" size="16" type="text" value="" readonly>
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                                </div>
                                <input type="hidden" class="dtp_endSales" id="dtp_endSales" value="" /><br/>
                            </div>
                        </span>
                    </span>
                    <div>
                        <button id="newTicket" type="button" class="btn btn-default">新增票種</button>
                    </div>
                    <button id="editEvent" type="button" class="btn btn-default">上一步</button>
                    <button id="editForm" type="button" class="btn btn-default">下一步</button>
                </div>
                <div class="row" id="divEditForm" style="display:none;">
                    <h1>設定表單</h1>
                    <div class="col-cg-6">
                    <table class="table table-bordered">
                        <tr>
                            <th>必填</th>
                            <th>欄位</th>
                            <th>範例表格</th>
                        </tr>
                        <tbody>
                        <?php foreach ($this->forms as $data): ?>
                            <tr>
                                <td>
                                    <div class="form-group checkbox">
                                        <label>
                                            
                                            <?php echo $this->formCheckbox('form[' . $data['name']. ']') ?>
                                        </label>
                                    </div>
                                </td>
                                <td>
                                    <?php echo $data['formName'] ?>
                                </td>
                                <td>
                                    <div class="form-group">
                                        
                                        <?php echo $this->formText('xxx', null, array('class' => 'form-control', 'placeholder' => $data['placeholder'])) ?>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach ?>
                            <tr>
                                <td>
                                    <div class="form-group checkbox">
                                        <label>
                                            <input type="checkbox" value="1" name="form[birthday]">
                                        </label>
                                    </div>
                                </td>
                                <td>
                                    生日
                                </td>
                                <td>
                                    <div class="form-group form-inline">
                                        <label class="control-label">西元</label>
                                        <input class="form-control" placeholder="19xx">
                                        <label class="control-label">年</label>
                                        <input class="form-control" placeholder="8">
                                        <label class="control-label">月</label>
                                        <input class="form-control" placeholder="20">
                                        <label class="control-label">日</label>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="form-group checkbox">
                                        <label>
                                            <input type="checkbox" value="1" name="form[gender]">
                                        </label>
                                    </div>
                                </td>
                                <td>
                                    性別
                                </td>
                                <td>
                                    <div class="form-group">
                                        <?php echo $this->formSelect('xxx', 1, array('class' => 'form-control'), array(1 => '--', 2 => '男', 3 =>'女')) ?>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="form-group checkbox">
                                        <label>
                                            <input type="checkbox" value="1" name="form[group]">
                                        </label>
                                    </div>
                                </td>
                                <td>
                                    牧區
                                </td>
                                <td>
                                    <div class="form-group">
                                        <?php echo $this->formSelect('xxx', 0, array('class' => 'form-control'), $this->groups) ?>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="form-group checkbox">
                                        <label>
                                            <input type="checkbox" value="1" name="form[food]">
                                        </label>
                                    </div>
                                </td>
                                <td>
                                    飲食
                                </td>
                                <td>
                                    <div class="form-group">
                                        <?php echo $this->formSelect('xxx', 1, array('class' => 'form-control'), array(1 => '--', 2 => '葷食', 3 =>'素食', 4 => '不訂便當')) ?>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="form-group checkbox">
                                        <label>
                                            <input type="checkbox" value="1" name="form[other]">
                                        </label>
                                    </div>
                                </td>
                                <td>
                                    其他事項
                                </td>
                                <td>
                                    <div class="form-group">
                                        <textarea cols="80" class="form-control" rows="10"></textarea>   
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <!-- 
                        <div class="form-group">
                            <label>設定表單</label>
                            <input class="form-control" placeholder="例如：一般票、學生票">
                            <p class="help-block">Example block-level help text here.</p>
                        </div>
                        <div class="form-group checkbox">
                            <label>
                        <input type="checkbox"> Remember me
                            </label>
                        </div>
                     --> 
                        <button id="backTicket" type="button" class="btn btn-default">上一步</button>
                        <button id="submit" type="submit" class="btn btn-default">完成</button>
                    </div>
                </div>
            </div>
        </form>